import NavBar from "@/components/nav/NavBar";
import Head from "next/head";
import React from "react";

function Singeltour() {
  return (
    <div>
      <Head>
        <title>CAIRO_PYRAMIDS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  );
}

export default Singeltour;
